/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sdfs.directoryservice.ui;

import org.sdfs.interfaces.GlobalConfig;

/**
 *
 * @author icarojerry
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainWindow() {
        initComponents();
        this.setTitle( GlobalConfig.APP_TITLE+ " :: Directory Service");
        initScene = new InitialScene();
        tabContainer.add(initScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(initScene), "Log Scene");
        
        serverScene = new ServersScene();
        tabContainer.add(serverScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(serverScene), "Connected Servers");
        
        usersScene = new UsersScene();
        tabContainer.add(usersScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(usersScene), "Connected Users");
    }
    
    public void printLog(String typeMessage, String message) {
        this.initScene.printLog(typeMessage, "- " + message);
    }
    
    
    public void refreshAllScenes() {
        usersScene.refreshScene();
        serverScene.refreshScene();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private InitialScene initScene;
    private ServersScene serverScene;
    private UsersScene usersScene;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContainer;
    // End of variables declaration//GEN-END:variables

}
