/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sdfs.directoryservice.ui;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.sdfs.directoryservice.controller.DirectoryServiceController;
import org.sdfs.interfaces.model.IServer;
import org.sdfs.interfaces.model.ServerTableModel;

/**
 *
 * @author icarojerry
 */
public class ServersScene extends javax.swing.JPanel {

    /**
     * Creates new form ServersScene
     */
    public ServersScene() {
        initComponents();
        
        tblListServers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListServers.setAutoCreateRowSorter(true);
        tblListServers.setShowVerticalLines(false);
        
        listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                int row = tblListServers.getSelectionModel().getLeadSelectionIndex();
                //atribuir acao ao ser selecionada uma linha da tabela
            }
        };
        tblListServers.getSelectionModel().addListSelectionListener(listSelectionListener);

    }
    public void refreshScene() {
        setTableData();
    }
    private void setTableData() {
        IServer[] servers;
        
        if(DirectoryServiceController.getInstance().getAvailableServers() == null ||
           DirectoryServiceController.getInstance().getAvailableServers().getAllServers().size() == 0)
            return;

        
        servers = new IServer[DirectoryServiceController.getInstance().getAvailableServers().getAllServers().size()];
        
        for(int i = 0; i < servers.length; ++i) {
            servers[i] = DirectoryServiceController.getInstance().getAvailableServers().getAllServers().get(i);
        }
        
        if (serverTableModel == null) {
            serverTableModel = new ServerTableModel();
            tblListServers.setModel(serverTableModel);
        }
        tblListServers.getSelectionModel().removeListSelectionListener(listSelectionListener);
        serverTableModel.setServers(servers);
        tblListServers.getSelectionModel().addListSelectionListener(listSelectionListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serversScrollPane1 = new javax.swing.JScrollPane();
        tblListServers = new javax.swing.JTable();

        tblListServers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListServers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serversScrollPane1.setViewportView(tblListServers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serversScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serversScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private ServerTableModel serverTableModel;
    private  ListSelectionListener listSelectionListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane serversScrollPane1;
    private javax.swing.JTable tblListServers;
    // End of variables declaration//GEN-END:variables

}
