/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sdfs.directoryservice.ui;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.sdfs.directoryservice.controller.DirectoryServiceController;
import org.sdfs.interfaces.model.IUser;
import org.sdfs.interfaces.model.UserTableModel;

/**
 *
 * @author icarojerry
 */
public class UsersScene extends javax.swing.JPanel {

    /**
     * Creates new form ServersScene
     */
    public UsersScene() {
        initComponents();
        
        tblListUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListUsers.setAutoCreateRowSorter(true);
        tblListUsers.setShowVerticalLines(false);
        
        listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                int row = tblListUsers.getSelectionModel().getLeadSelectionIndex();
                //atribuir acao ao ser selecionada uma linha da tabela
            }
        };
        tblListUsers.getSelectionModel().addListSelectionListener(listSelectionListener);

    }
    public void refreshScene() {
        setTableData();
    }
    private void setTableData() {
        IUser[] users;
        
        if(DirectoryServiceController.getInstance().getConnectedUsers()== null || 
           DirectoryServiceController.getInstance().getConnectedUsers().size() == 0)
            return;
        
        users = new IUser[DirectoryServiceController.getInstance().getConnectedUsers().size()];
        for(int i = 0; i < users.length; ++i) {
            users[i] = DirectoryServiceController.getInstance().getConnectedUsers().get(i);
        }
        
        if (userTableModel == null) {
            userTableModel = new UserTableModel();
            tblListUsers.setModel(userTableModel);
        }
        tblListUsers.getSelectionModel().removeListSelectionListener(listSelectionListener);
        userTableModel.setUsers(users);
        tblListUsers.getSelectionModel().addListSelectionListener(listSelectionListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serversScrollPane1 = new javax.swing.JScrollPane();
        tblListUsers = new javax.swing.JTable();

        tblListUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serversScrollPane1.setViewportView(tblListUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serversScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serversScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private UserTableModel userTableModel;
    private  ListSelectionListener listSelectionListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane serversScrollPane1;
    private javax.swing.JTable tblListUsers;
    // End of variables declaration//GEN-END:variables
}
