/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sdfs.server.ui;

import java.awt.Container;
import org.sdfs.interfaces.GlobalConfig;
import org.sdfs.server.controller.ServerController;

/**
 *
 * @author icarojerry
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainWindow() {
        initComponents();
        
        this.setTitle( GlobalConfig.APP_TITLE+ " :: Server");
        initScene = new InitializeScene();
        tabContainer.add(initScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(initScene), "Config Server");
        
        logScene = new LogScene();
        tabContainer.add(logScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(logScene), "Log Area");
        
        usersScene = new UsersScene();
        tabContainer.add(usersScene);
        tabContainer.setTitleAt(tabContainer.getComponentZOrder(usersScene), "Connected Users");
  
        mainPanel = getContentPane();
        setContentPane(initScene);
    }
    
    public void refreshAllScreen() {
        if(ServerController.getInstance().isConnected2DS()) {
                setContentPane(mainPanel);
        }

        revalidate();
        repaint();
    }
    public void setEnableLoadConfigOpt(boolean opt) {
        initScene.getBntLoadPreviousData().setEnabled(opt);
        initScene.getBntLoadPreviousData().setVisible(opt);
    } 
    
    public void printLog(String typeMessage, String message) {
        this.logScene.printLog(typeMessage, "- " + message);
    }
    
    public void dataServerChanged() {
        if(this.getContentPane() == initScene) {
            initScene.setTxtServiceAddr(ServerController.getInstance().getDataServer().getServiceAddr());
            initScene.setTxtServicePort(""+ ServerController.getInstance().getDataServer().getServicePort());
            initScene.setTxtAlias(ServerController.getInstance().getDataServer().getServerAlias());
            initScene.setTxtPort("" + ServerController.getInstance().getDataServer().getServerPort());
            initScene.setTxtDataDir(ServerController.getInstance().getDataServer().getServerDataDir());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private InitializeScene initScene;
    private LogScene logScene;
    private UsersScene usersScene;
    private Container mainPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContainer;
    // End of variables declaration//GEN-END:variables
}
