/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sdfs.client.ui;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.sdfs.client.controller.ClientController;
import org.sdfs.interfaces.model.IServer;
import org.sdfs.interfaces.model.IUser;
import org.sdfs.interfaces.model.ServerTableModel;

/**
 *
 * @author icarojerry
 */
public class ServersScene extends javax.swing.JPanel {

    /**
     * Creates new form ServersScene
     */
    public ServersScene() {
        initComponents();
        
        tblListServers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListServers.setAutoCreateRowSorter(true);
        tblListServers.setShowVerticalLines(false);
        
        listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                int row = tblListServers.getSelectionModel().getLeadSelectionIndex();
                //atribuir acao ao ser selecionada uma linha da tabela
            }
        };
        tblListServers.getSelectionModel().addListSelectionListener(listSelectionListener);

    }
    public void refreshScene() {
        setTableData();
    }
    private void setTableData() {
        IServer[] servers;
        
        if(ClientController.getInstance().getAvailableServers() == null ||
           ClientController.getInstance().getAvailableServers().getAllServers().size() == 0)
            return;

        
        servers = new IServer[ClientController.getInstance().getAvailableServers().getAllServers().size()];
        
        for(int i = 0; i < servers.length; ++i) {
            servers[i] = ClientController.getInstance().getAvailableServers().getAllServers().get(i);
        }
        
        if (serverTableModel == null) {
            serverTableModel = new ServerTableModel();
            tblListServers.setModel(serverTableModel);
        }
        tblListServers.getSelectionModel().removeListSelectionListener(listSelectionListener);
        serverTableModel.setServers(servers);
        tblListServers.getSelectionModel().addListSelectionListener(listSelectionListener);
        
        if(!ClientController.getInstance().isConnected2SRV())
            tblListServers.setRowSelectionInterval(0, 0);
        else { 
            int i = serverTableModel.getRowByServer(ClientController.getInstance().getConnectedServer());
            tblListServers.setRowSelectionInterval(i, i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serversScrollPane1 = new javax.swing.JScrollPane();
        tblListServers = new javax.swing.JTable();
        btnServerConnect = new javax.swing.JButton();

        tblListServers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListServers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serversScrollPane1.setViewportView(tblListServers);

        btnServerConnect.setText("Connect");
        btnServerConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serversScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnServerConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serversScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServerConnect)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServerConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerConnectActionPerformed
        int row = tblListServers.getSelectedRow();
        IServer s = (IServer) serverTableModel.getServer(row);
        
        ClientController.getInstance().connectToServer(s);
    }//GEN-LAST:event_btnServerConnectActionPerformed

    private ServerTableModel serverTableModel;
    private  ListSelectionListener listSelectionListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServerConnect;
    private javax.swing.JScrollPane serversScrollPane1;
    private javax.swing.JTable tblListServers;
    // End of variables declaration//GEN-END:variables
}
